---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-editor
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["create", "delete", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxy-controller
  namespace: default
subjects:
  - kind: ServiceAccount
    name: proxy-controller
roleRef:
  kind: Role
  name: deployment-editor
  apiGroup: rbac.authorization.k8s.io
